site_name: Magewire PHP (Beta)
site_description: Magewire PHP Documentation
site_url: https://magewirephp.github.io/magewire-docs/

use_directory_urls: false

theme:
  name: material
  custom_dir: overrides
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.path
    - navigation.tabs
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.prune
    - navigation.top
    - navigation.indexes
    - content.code.copy
    - content.code.annotate
    - content.code.select
    - header.autohide
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra_css:
  - stylesheets/style.css

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://x.com/magewirephp
  generator: false
  analytics:
    provider: custom
  includes:
    dir: includes

markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - blog:
      enabled: true
      post_readtime: true
      blog_dir: blogs
  - tags:
      enabled: true
  - privacy:
      enabled: !ENV
  - search:
      enabled: true
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - macros:
      include_dir: includes

nav:
  - 'Getting Started':
      - 'index.md'
      - 'pages/getting-started/basics.md'
      - 'pages/getting-started/beta.md'
      - 'pages/getting-started/contribute.md'
      - 'pages/getting-started/documentation.md'
      - 'pages/getting-started/examples.md'
      - 'pages/getting-started/faq.md'
      - 'pages/getting-started/license.md'
      - 'pages/getting-started/notables.md'
      - 'pages/getting-started/purpose.md'
      - 'pages/getting-started/sponsoring.md'
      - 'pages/getting-started/upgrade.md'
      - 'Releases':
        - 'pages/getting-started/releases/feature-history.md'
        - 'pages/getting-started/releases/changelog.md'
  - 'Essentials':
      - 'pages/essentials/components.md'
      - 'pages/essentials/properties.md'
      - 'pages/essentials/actions.md'
      - 'pages/essentials/events.md'
      - 'pages/essentials/lifecycle-hooks.md'
      - 'pages/essentials/nesting-components.md'
      - 'pages/essentials/testing.md'
  - 'Features':
      - 'pages/features/alpine.md'
      - 'pages/features/magewire-flakes.md'
      - 'pages/features/magewire-template-directives.md'
      - 'pages/features/request-bundling.md'
      - 'pages/features/offline-states.md'
  - 'Directives':
      - 'pages/html-directives/wire-click.md'
      - 'pages/html-directives/wire-submit.md'
      - 'pages/html-directives/wire-model.md'
      - 'pages/html-directives/wire-loading.md'
      - 'pages/html-directives/wire-current.md'
      - 'pages/html-directives/wire-cloak.md'
      - 'pages/html-directives/wire-dirty.md'
      - 'pages/html-directives/wire-confirm.md'
      - 'pages/html-directives/wire-transition.md'
      - 'pages/html-directives/wire-init.md'
      - 'pages/html-directives/wire-poll.md'
      - 'pages/html-directives/wire-offline.md'
      - 'pages/html-directives/wire-ignore.md'
      - 'pages/html-directives/wire-replace.md'
      - 'pages/html-directives/wire-show.md'
      - 'pages/html-directives/wire-stream.md'
      - 'pages/html-directives/wire-text.md'
  - 'Concepts':
    - 'pages/concepts/fragments.md'
    - 'pages/concepts/morphing.md'
    - 'pages/concepts/hydration.md'
    - 'pages/concepts/nesting.md'
  - 'Advanced':
    - 'pages/advanced/best-practices.md'
    - 'pages/advanced/patterns.md'
    - 'pages/advanced/security.md'
    - 'pages/advanced/synthesizers.md'
    - 'pages/advanced/themes.md'
    - 'pages/advanced/troubleshooting.md'
    - 'Javascript':
        - 'pages/advanced/javascript/index.md'
        - 'Addons':
            - 'pages/advanced/javascript/addons/magewire-notifier.md'
        - 'Utilities':
            - 'pages/advanced/javascript/utilities/dom.md'
            - 'pages/advanced/javascript/utilities/loader.md'
            - 'pages/advanced/javascript/utilities/str.md'
    - 'Architecture':
        - 'pages/advanced/architecture/component-hooks.md'
        - 'pages/advanced/architecture/index.md'
        - 'pages/advanced/architecture/facades.md'
        - 'pages/advanced/architecture/features.md'
        - 'Mechanisms':
            - 'pages/advanced/architecture/mechanisms/index.md'
            - 'pages/advanced/architecture/mechanisms/resolvers.md'
        - 'pages/advanced/architecture/layout.md'
        - 'pages/advanced/architecture/portman.md'
  - 'Blog':
      - 'blogs/index.md'
