
site_name: Magewire Docs
site_description: Magewire Developer Documentation
site_url: https://magewire.wpoortman.nl/
copyright: Copyright &copy; Hyvä Themes 2020-present. All rights reserved.
#repo_url: https://github.com/magewirephp/magewire-docs.git

# Keep use_directory_urls as false, otherwise it will break internal links, the slackbot and who knows what else
use_directory_urls: false

theme:
  name: material
  custom_dir: overrides
  logo: images/hyva-logo-192x192.png
  favicon: images/hyva-logo-192x192.png
  features:
    - navigation.tabs
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra_javascript:
  - js/search-focus.js

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/magewirephp
  generator: false
  analytics:
    provider: custom

markdown_extensions:
  - abbr
  - pymdownx.highlight:
      anchor_linenums: true
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - 'Welcome!':
    - 'welcome/what-is-magewire.md'
