site_name: Magewire PHP Docs
site_description: Magewire PHP Developer Documentation
site_url: https://magewire-docs.wpoortman.nl/

# Keep use_directory_urls as false, otherwise it will break internal links, the slackbot and who knows what else
use_directory_urls: false

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.footer
    - navigation.instant
    - navigation.tracking
    - navigation.prune
    - navigation.top
    - navigation.indexes
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra_css:
  - stylesheets/style.css

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://x.com/magewirephp
  generator: false
  analytics:
    provider: custom

markdown_extensions:
  - abbr
  - pymdownx.highlight:
      anchor_linenums: true
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - blog:
      enabled: true
      post_readtime: true
      blog_dir: blogs
  - tags:
      enabled: true
  - privacy:
      enabled: !ENV
  - social:
      enabled: true
      cards: true
  - search:
      enabled: true
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - redirects: {}

nav:
  - 'Getting Started':
      - 'pages/getting-started/quickstart.md'
      - 'pages/getting-started/installation.md'
      - 'pages/getting-started/upgrade-guide.md'
  - 'Essentials':
      - 'pages/essentials/components.md'
      - 'pages/essentials/properties.md'
      - 'pages/essentials/actions.md'
      - 'pages/essentials/events.md'
      - 'pages/essentials/lifecycle-hooks.md'
      - 'pages/essentials/nesting-components.md'
      - 'pages/essentials/testing.md'
  - 'Features':
      - 'pages/features/alpine.md'
      - 'pages/features/navigate.md'
      - 'pages/features/lazy-loading.md'
      - 'pages/features/validation.md'
  - 'Blog':
      - 'blogs/index.md'
